version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports: 
    - 27017:27017
    volumes: 
    - /data/bitcore/db:/data/db
    
  bitcore-node:
    image: bitcore-node
    links:
      - database
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
    env_file: .env
    command: ["npm", "--prefix=./packages/bitcore-node", "start"]

  nginx:
    image: insight-previous-nginx
    hostname: "insight-previous-nginx"
    
    ports:
      - "443:443"
      - "80:80"

networks:
  host:
    driver: host
  
