version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports: 
    - 27017:27017
    volumes: 
    - /data/db:/data/db
    
  bitcore-node:
    build: .
    image: bitcore-node
    links:
      - database
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=database
    env_file: .env
    # command: npm --prefix=./packages/bitcore-node start
    command: ["npm", "--prefix=./packages/bitcore-node", "start"]

  insight:
    image: bitcore-node
    links:
      - bitcore-node
    environment:
      - API_URL=bitcore-node
    # ports:
    #   - 14200:4200
    command: ["npm", "--prefix=./packages/insight", "start"]

networks:
  default:
    driver: host
