version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports: 
    - 27017:27017
    volumes: 
    - ./data/bitcore/db:/data/db
    
  bitcore-node:
    build: .
    image: bitcore-node
    links:
      - database
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
    env_file: .env
    command: ["npm", "--prefix=./packages/bitcore-node", "start"]

  nginx:
    build: "./packages/insight/"
    image: bitcore-nginx
    hostname: "nginx"
    links:
      - bitcore-node
    
    ports:
      - "18443:443"
      - "8080:80"

networks:
  host:
    driver: host
  
